### ISSUE TITLE
When .ojul/update.sh is added to cron, all files and folders form $HOME are deleted

### ISSUE THREAD

**Issue by fazlerabbi37** [ashikuzzaman-ar/ojul#3]
When .ojul/update.sh is added to cron, it all files and folder from `$HOME` is deleted. 
Crontab syntex
`00 21 * * * /home/fazlerabbi37/.ojul/update.sh >> /home/fazlerabbi37/.ojul/cron.tab 2>&1`
By checking the contains of cron.tab we can see that cron can't retrieve the value of `$USER` so it stays on `$HOME` folder and renames all files and folders of `$HOME` to `java` resulting in deletion of all files and folders. 
See this [asciicast](https://asciinema.org/a/148266) for details.

**Comment by ashikuzzaman-ar** [comment]
Dear Brother,
Thank you for your contribution and good concern about this project. First
of all, I'm very sorry to merge your pull request too late because of my
illness. I'm going to update the version with more functionality and I need
your help to do that. I hope you would like to contribute there.

Thank you very much and best regards.

**Comment by fazlerabbi37** [comment]
Actually I should be thanking you as it was my first accepted pull requested and I would love to help this project in future.
